FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder

EXPOSE 8000/tcp

WORKDIR /app

COPY requirements.txt /app
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT ["python3"]
CMD ["app.py"]
