name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - "staging" # only execute this workflow when I’m pushing to “staging”

env:
  AWS_ROLE: arn:aws:iam::637423617370:role/GitHub-actions-role
  AWS_REGION: us-west-2

jobs:
  deploy:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    # Permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      
      # Deploy cluster
      - name: Deploys my cluster
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.APP_NAME }}-cluster
          template: ./cluster_formation.yaml
          no-fail-on-empty-changeset: "1"

